# string processing
print("oanh".capitalize())
print("oanh".casefold())
print("oanh".center(1, "d"))
print("oanh" * 3 + "van kem")
print('oanh' 'van kem')
print('pham van oanh'[-1])
print('pham van oanh'[-2])
print('pham van oanh'[-3])
print('pham van oanh'[-3:-1])
print('pham van oanh'[-13:])
print('pham van oanh'[0:])
print('pham anh'[0:10000])
print('pham oanh'[:-10000])
print('pham van '[:])
